### ISSUE TITLE
Running a test in debug mode stopped working

### ISSUE THREAD

**Issue by sam-wright** [hdevalke/rust-test-lens#3]
A couple weeks ago I noticed that the "Debug Test" stopped working. The "Run Test" still works though. This has been confirmed on multiple machines, Ubuntu 18.04 and Ubuntu 18.04, both using the rustup beta channel (although switching to stable didn't fix it either)

**Comment by hdevalke** [comment]
Do you have a minimal example of a test that stopped working? Could you provide some logs from this extension or the code-lldb extension? You can find them in the output tab.

**Comment by sam-wright** [comment]
Interesting.

On a new example project it does work, yielding:
```
Display settings: variable format=auto, show disassembly=auto, numeric pointer values=off, container summaries=on.
Launching /home/sam/Sandbox/test_test/target/debug/test_test-ff9bfbb506f2465d it_works
Module loaded: /lib/x86_64-linux-gnu/ld-2.28.so. Symbols loaded.
Module loaded: [vdso].
Module loaded: /home/sam/Sandbox/test_test/target/debug/test_test-ff9bfbb506f2465d. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libdl.so.2. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/librt.so.1. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libpthread.so.0. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libgcc_s.so.1. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libc.so.6. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libm.so.6. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libdl.so.2. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/librt.so.1. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libpthread.so.0. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libgcc_s.so.1. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libc.so.6. Symbols loaded.
Module loaded: /lib/x86_64-linux-gnu/libm.so.6. Symbols loaded.

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Process exited with code 0.
```

but running on my current project only yields:

```
Running `cargo test --no-run --package=xxmy_projectxx --message-format=json`...
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
Matching compilation artifacts: 
```

What are some things that I could have done to cause my project to stop working? I am pulling in some things via FFI, but otherwise its a pretty straightforward project...

**Comment by hdevalke** [comment]
I will try to reproduce your problem, but it would really help if you could strip down your project to trigger the same behaviour. Which version of vscode, rust and cargo do you have?

could you run:

```
$ code --version && cargo --version && rustc --version
1.32.1
05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
x64
cargo 1.33.0 (f099fe94b 2019-02-12)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by sam-wright** [comment]
```
code --version && cargo --version && rustc --version

1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64
cargo 1.34.0-beta (5c6aa46e6 2019-02-22)
rustc 1.34.0-beta.1 (744b374ab 2019-02-26)
```

This is on Ubuntu 18.10, with vscode installed via snap

**Comment by hdevalke** [comment]
I installed the same version of rust and cargo on ubuntu 18.10. I have code 1.32.1. 
I created a project with multiple binaries and a library and with integration tests. In all files I can debug tests. Do you have multiple crates in the project?

Also, did you try to restart vscode? There is some caching when opening the project.

**Comment by sam-wright** [comment]
my project specifically is a static-lib (single target) with the following crates pulled in:
```
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
regex = "^1"
logging-allocator = "0.1.1"
log = "0.4"
simple_logger = "1.0"
heapless = "0.4.2"
```

We've restarted many times, as this has been noticed for weeks. 

* side-note, its surprising that the vscode snap package is slightly behind, isn't that one of the key point of snap packages? I assume you've installed via their deb?

**Comment by hdevalke** [comment]
I installed code using snap to have the 1.31.1 version, but could not reproduce the problem.
I installed code 1.32.1 using the debian repo as described on the vscode [website](https://code.visualstudio.com/#alt-downloads).

The dependencies, nor using FFI should have impact on the workings of the plugin. 

You could try to debug this plugin yourself:

Clone this repo and open the folder in vscode. You should be able to debug the extension, which will open a new vscode window.

The plugin will make a new debug configuration, which will be launched using the lldb-code plugin.
Put a breakpoint at [extension.ts:31](https://github.com/hdevalke/rust-test-lens/blob/master/src/extension.ts#L31) and evaluate the value of the variable `debugConfig`.

This will probably give some hint.

If the problem would be with the codelldb plugin, you can add more verbose logging setting  `lldb.verboseLogging` on `true`.

**Comment by sam-wright** [comment]
Running inside the "Extension Development Host" it never seems to find the plugin (even on other projects that this plugin currently _does_ work for) although I'm quite outside my element...

```
Activating extension 'hdevalke.rust-test-lens' failed: Cannot find module '/home/sam/Sandbox/rust-test-lens/out/extension'.
extensionHostProcess.js:735
Activating extension `hdevalke.rust-test-lens` failed:  Cannot find module '/home/sam/Sandbox/rust-test-lens/out/extension'
extensionHostProcess.js:331
Here is the error stack:  Error: Cannot find module '/home/sam/Sandbox/rust-test-lens/out/extension'
extensionHostProcess.js:331
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/snap/vscode/87/usr/share/code/resources/app/out/vs/loader.js:31:542)
	at /snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:5
	at t._doActivateExtension (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:113)
	at t._activateExtension (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:738:785)
	at Object.actualActivateExtension (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:735:633)
	at e._activateExtension (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:330:969)
	at /snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:330:592
	at Array.map (<anonymous>)
	at e._activateExtensions (/snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:330:567)
	at /snap/vscode/87/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:330:699
Setting sysroot to /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
extension.js:360
running with rustup: rls
extension.js:388
will use a rustup-installed RLS; ensuring present
```

**Comment by hdevalke** [comment]
You probably have to run `npm install` once in the root of the project.

I would like to help you, but I really need to to be able to reproduce this issue. If you could strip down (maybe use [`unimplemented!()`](https://doc.rust-lang.org/std/macro.unimplemented.html) to only keep the method under test) that would really help. 

If that is not possible, maybe the output of `cargo metadata --no-deps --format-version=1` might give some clue.

**Comment by sam-wright** [comment]
No problem, I really appreciate you helping and thinking through this with me.

Does 
```
    let out_dir = env::current_dir().unwrap();
    println!("cargo:rustc-link-search=native={}", out_dir.display()); 
```
in the `build.rs` affect the plugin in any way? this is the only project I've needed to link in the FFI this way.

**Comment by hdevalke** [comment]
I added that to a project that has a `build.rs` file, but it does not trigger an issue. I found an issue where the project has 2 files in the `./tests` directory. Clicking on Debug make vscode popup:

> Cargo has produced more than one binary artifact.

Is that also your problem?

**Comment by sam-wright** [comment]
`npm install` is all that was needed to get your project running. 
I looked through a working project's "Debug Tests" and the non-working projects "Debug Test". The non-working project reports:
```
[vadimcn.vscode-lldb] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'lldb.adapterType', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:401
[vadimcn.vscode-lldb] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'lldb.dbgconfig', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:401
rejected promise not handled within 1 second
```

The working project prints the top 2 messages, but not the `rejected promise not handled within 1 second`
and at first glance, the `debugConfig` looks the same.

**Comment by sam-wright** [comment]
> Is that also your problem?

No, I have many submodules, that individually have a `unit_tests.rs` submodule, but none that match what you're describing.

I will probably start stripping it back like you mentioned soon

**Comment by sam-wright** [comment]
I have stripped it down and gotten it to start working. I have not yet singled out a single component that is causing the trouble. One thing I've noticed is that _the "badness" only begins once I restart vscode_
i.e. I can one-by-one add modules and crates back in and this plugin continues working until I restart vscode...

Also, does this output seem relevant (from the Output Log (Window)):
```
[2019-03-20 13:22:41.306] [renderer21] [error] Cannot read property 'fileName' of undefined: Error: Cannot read property 'fileName' of undefined
    at debugService.startDebugging.then.e (file:///snap/vscode/89/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3159:592)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hdevalke** [comment]
That exception comes from the vscode-lldb extension at [cargo.ts:60](https://github.com/vadimcn/vscode-lldb/blob/ed956cefe3911bd96e7bbbd5b847a137822d548c/extension/cargo.ts#L60).

As this extension is only creating a debug configuration and passes it on to the vscode-lldb extension. 

There could be a bug in what this extension creates as debug configuration, which makes cargo not finding any test binary to run.

Can you debug using only the lldb extension?

In vscode press `CTRL+P` and search for `LLDB: Generate lauch configuration from Cargo.toml`.

copy the contents of the created configuration in a file `./.vscode/launch.json`:

```javascript
{
    "version": "0.2.0",
    "configurations": // ADD CREATED CONFIG HERE
}
```

You should be able to download and debug your tests here:
![Screenshot from 2019-03-20 22-03-27](https://user-images.githubusercontent.com/2261239/54718992-0eddc480-4b5c-11e9-93ae-3f7f809d171b.png)

**Comment by sam-wright** [comment]
Ok, I get a popup in the lower-right that says:
`Cannot read property 'fileName' of undefined`

for clarity, the workspace file now looks like: 
```

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug unit tests in library 'xxxx'",
            "cargo": {
                "args": [
                    "test",
                    "--no-run",
                    "--lib",
                    "--package=xxxx"
                ],
                "filter": {
                    "kind": "lib"
                }
            },
            "args": [],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

**Comment by sam-wright** [comment]
also of note -- If I use the "LLDB: Debug Cargo Tests" instead, it does successfully launch all the tests in debug mode.

**Comment by hdevalke** [comment]
If that one fails, it is probably a bug in vscode-lldb. 

The output of 

```sh
cargo test --no-run --lib --package=xxxx --message-format=json 2>/dev/null | jq
```

might reveal why [cargo.ts:32](https://github.com/vadimcn/vscode-lldb/blob/ed956cefe3911bd96e7bbbd5b847a137822d548c/extension/cargo.ts#L32) generates an artifact without a filename, but than it is better to open a ticket in that repository.

**Comment by hdevalke** [comment]
Didn't see your last comment. So it is probably bug in what is sent as debug configuration.

Could you debug and put a breakpoint [extension.ts:31](https://github.com/hdevalke/rust-test-lens/blob/master/src/extension.ts#L31) to print the value of `debugConfig`? 

That configuration probably triggers the bug.

**Comment by hdevalke** [comment]
I added a branch [bug-3](https://github.com/hdevalke/rust-test-lens/tree/bug-3) to print the debug config in the output window.

it will output something like 

```
Debugging: {
  "type": "lldb",
  "request": "launch",
  "name": "Debug test_day_9_10 in day9.rs",
  "cargo": {
    "args": [
      "test",
      "--no-run",
      "--package=aoc2018",
      "--bin=day9"
    ],
    "filter": {
      "kind": "bin"
    }
  },
  "args": [
    "test_day_9_10"
  ],
  "cwd": "/home/hannes/code/aoc2018"
}
```

If you run cargo with the args plus `--message-format=json` you should see some filename for a binary for the test.

**Comment by hdevalke** [comment]
I could replicate the issue. I hope I can find out the problem soon.

**Comment by hdevalke** [comment]
Found the cause. But a solution will take some time.
I will have to use `cargo test --no-run --tests prettier --message-format json` instead of `cargo metadata --no-deps --format-version=1` to match each main or test function to have the right kind and name of the  binary to run.


```js
{
  "reason": "compiler-artifact",
  "package_id": "sqltools 0.1.0 (path+file:///home/.../bin_name)",
  "target": {
    "kind": [
      "bin"
    ],
    "name": "sqltools",
    "src_path": "/home/.../src/main.rs",
  },
  "profile": {
    "test": false
  },
  "executable": "/home/.../target/debug/bin_name",
}
```

The `profile.test` can be used to distinguish between main function and test functions. The longest match between the filename of the test and `src.path` can be used to find the right executable.

**Comment by sam-wright** [comment]
Excellent! I'm happy to run any tests you want once you think you have something.

I'd be very curious to know what is so unique about this project to cause this problem, since this plugin seems to work great on every other project. (Node is entirely foreign to me so I still only partially follow what the problem is)

**Comment by hdevalke** [comment]
The branch `bug-3` should solve the problem. It was caused when having a crate of type binary and testing a test in another file than `main.rs`. Could you verify this, before I create a new release?

**Comment by sam-wright** [comment]
I pulled your new changes, but this did not change anything. However, there is something wrong with my setup running from the git repo :
![image](https://user-images.githubusercontent.com/1241069/54927790-78e9c700-4ed8-11e9-9096-421deead5783.png)
This might have been there before, I am not sure, but I just noticed some errors in the rust-test-lens project. So my test might not be valid.

**Comment by hdevalke** [comment]
You probably have to do an `npm install`.
I'll make a new release with the changes already done. It will make it easier for you to test. At least it solved a similar problem I could reproduce. If it is not solved I can search further to find out your problem.

**Comment by hdevalke** [comment]
It has been released, you should have receive the update soon in vscode.

![image](https://user-images.githubusercontent.com/2261239/54947509-c7c84880-4f3a-11e9-9649-8f051661c189.png)

**Comment by sam-wright** [comment]
This did not solve it unfortunately. Looks like you solved another bug along the way. 

I suspect we're more limited by my ability to describe the problem than anything else. I think I might try to put together a simple screen recording directly showing the behavior.

**Comment by sam-wright** [comment]
1) I fixed the missing npm files and it runs without error now.
2) I think the relevant debug output is: 
 
```
[vadimcn.vscode-lldb] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'lldb.adapterType', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:374
[vadimcn.vscode-lldb] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'lldb.dbgconfig', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:374
rejected promise not handled within 1 second: Error: Cannot read property 'fileName' of undefined
extensionHostProcess.js:700
stack trace: Error: Cannot read property 'fileName' of undefined
extensionHostProcess.js:700
    at debugService.startDebugging.then.e (file:///snap/vscode/89/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3159:592)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I've created a [very short video](https://youtu.be/brgU_tzJSa8) walking through what I see.

**Comment by hdevalke** [comment]
I'll try to help you further, as you helped me already to solve another bug.

> Cannot read property 'fileName' of undefined

This is indeed the bug, but it happens because in vscode-lldb at [cargo.ts:42](https://github.com/vadimcn/vscode-lldb/blob/ed956cefe3911bd96e7bbbd5b847a137822d548c/extension/cargo.ts#L42) where all artifacts are filtered out. If you debug the extension you can put a breakpoint in `cargo.js` from the vscode-lldb extension under the loaded scripts: 

![image](https://user-images.githubusercontent.com/2261239/55112848-d00cb900-50dd-11e9-8c6f-24605761ee62.png)

A breakpoint at line 32 will probably tell you why all artifacts are filtered out.

I watched the video and one thing I noticed is that the unit tests are in a separate module. I'll try to simulate that in a project.

**Comment by hdevalke** [comment]
I tried to mimic your project structure, but debugging a test is still working.

**Comment by sam-wright** [comment]
I think I found it. The filter is explicitly looking for 
```
kind: "lib"
```
while this project is building:

``` 
kind: "staticlib"
```

so all of my tests get filtered out

**Comment by hdevalke** [comment]
I'll updated a project to build a staticlib.

```toml
[package]
name = "bug"
version = "0.1.0"
edition = "2018"

[lib]
crate-type= ["staticlib"]

[dependencies]
```

However, I cannot reproduce the bug. The filter contains staticlib and the resolved artifact too.

**Comment by hdevalke** [comment]
The filter is calculate in [RustTests:56](https://github.com/hdevalke/rust-test-lens/blob/master/src/RustTests.ts#L56). The behavior before was to use lib by default.

So you arrive in line 73:

```
if (target === undefined) {
    kind = bin === undefined ? "lib" : "bin";
}
```

probably nothing matches line 65:

```js
if (t.src_path === uri) {
```

**Comment by hdevalke** [comment]
I could replicate your problem, by adding an example target. The solution is nearby.

**Comment by hdevalke** [comment]
I created a new branch [`issue-3`](https://github.com/hdevalke/rust-test-lens/tree/issue-3) could you test that branch and confirm this solves your issue?

**Comment by sam-wright** [comment]
Congrats! and thanks! That fixes it!

**Comment by hdevalke** [comment]
Glad to hear and thank you too for reporting the issue. The extension works now much better than before for more complicated projects.

I am preparing a new release, you should soon have a new version in vscode.
